import { Company } from "./types";

// 浙江省企业示例数据(虚构,仅用于功能演示与接口未接入时回退)。
// 字段结构与真实接口映射后的结构一致。
export const MOCK_COMPANIES: Company[] = [
  {
    id: "mock-0001",
    name: "杭州云栖网络科技有限公司",
    status: "存续",
    creditCode: "91330106MA2XXXXX01",
    legalPerson: "张伟",
    registeredCapital: "5000万元人民币",
    establishDate: "2015-03-12",
    address: "浙江省杭州市西湖区文三路 100 号科技大厦 8 层",
    businessScope: "技术开发、技术服务、计算机软硬件开发；互联网信息服务；数据处理。",
    province: "浙江省",
  },
  {
    id: "mock-0002",
    name: "宁波甬城智能制造股份有限公司",
    status: "在业",
    creditCode: "91330200MA2XXXXX02",
    legalPerson: "李娜",
    registeredCapital: "12000万元人民币",
    establishDate: "2010-07-21",
    address: "浙江省宁波市鄞州区中山东路 588 号",
    businessScope: "智能装备制造、机械设备研发、工业自动化系统集成；货物进出口。",
    province: "浙江省",
  },
  {
    id: "mock-0003",
    name: "温州瓯越鞋业有限公司",
    status: "存续",
    creditCode: "91330300MA2XXXXX03",
    legalPerson: "王强",
    registeredCapital: "800万元人民币",
    establishDate: "2008-11-05",
    address: "浙江省温州市鹿城区双屿工业区",
    businessScope: "鞋类制造、销售；皮革制品加工；服装鞋帽零售。",
    province: "浙江省",
  },
  {
    id: "mock-0004",
    name: "义乌小商品国际贸易有限公司",
    status: "存续",
    creditCode: "91330782MA2XXXXX04",
    legalPerson: "陈芳",
    registeredCapital: "2000万元人民币",
    establishDate: "2013-05-18",
    address: "浙江省金华市义乌市国际商贸城三区",
    businessScope: "日用百货、工艺品、玩具批发零售；货物及技术进出口。",
    province: "浙江省",
  },
  {
    id: "mock-0005",
    name: "绍兴黄酒文化产业有限公司",
    status: "存续",
    creditCode: "91330600MA2XXXXX05",
    legalPerson: "赵敏",
    registeredCapital: "3600万元人民币",
    establishDate: "2006-09-30",
    address: "浙江省绍兴市越城区鉴湖路 18 号",
    businessScope: "黄酒酿造、销售；食品生产；酒文化旅游开发。",
    province: "浙江省",
  },
  {
    id: "mock-0006",
    name: "嘉兴港区新材料科技有限公司",
    status: "存续",
    creditCode: "91330400MA2XXXXX06",
    legalPerson: "张伟",
    registeredCapital: "8000万元人民币",
    establishDate: "2018-01-09",
    address: "浙江省嘉兴市嘉兴港区临港大道 9 号",
    businessScope: "新材料技术研发；高分子材料制造、销售；化工产品(不含危化品)销售。",
    province: "浙江省",
  },
  {
    id: "mock-0007",
    name: "台州湾汽车零部件有限公司",
    status: "在业",
    creditCode: "91331000MA2XXXXX07",
    legalPerson: "刘洋",
    registeredCapital: "4500万元人民币",
    establishDate: "2012-04-26",
    address: "浙江省台州市椒江区经济开发区",
    businessScope: "汽车零部件研发、制造、销售；模具设计与制造。",
    province: "浙江省",
  },
  {
    id: "mock-0008",
    name: "湖州太湖生态农业发展有限公司",
    status: "存续",
    creditCode: "91330500MA2XXXXX08",
    legalPerson: "李娜",
    registeredCapital: "1500万元人民币",
    establishDate: "2016-08-14",
    address: "浙江省湖州市吴兴区织里镇",
    businessScope: "农产品种植、加工、销售；生态旅游；农业技术推广服务。",
    province: "浙江省",
  },
  {
    id: "mock-0009",
    name: "金华火腿食品集团有限公司",
    status: "存续",
    creditCode: "91330700MA2XXXXX09",
    legalPerson: "孙磊",
    registeredCapital: "6000万元人民币",
    establishDate: "2004-12-01",
    address: "浙江省金华市婺城区食品工业园",
    businessScope: "肉制品加工、销售；食品生产；进出口贸易。",
    province: "浙江省",
  },
  {
    id: "mock-0010",
    name: "丽水山耕农林开发有限公司",
    status: "存续",
    creditCode: "91331100MA2XXXXX10",
    legalPerson: "周杰",
    registeredCapital: "1000万元人民币",
    establishDate: "2017-06-22",
    address: "浙江省丽水市莲都区碧湖镇",
    businessScope: "林木种植；农副产品加工销售；乡村旅游开发。",
    province: "浙江省",
  },
  {
    id: "mock-0011",
    name: "衢州数字经济服务有限公司",
    status: "存续",
    creditCode: "91330800MA2XXXXX11",
    legalPerson: "吴婷",
    registeredCapital: "2800万元人民币",
    establishDate: "2019-10-10",
    address: "浙江省衢州市柯城区智慧新城",
    businessScope: "软件开发；信息技术咨询；大数据服务；电子商务。",
    province: "浙江省",
  },
  {
    id: "mock-0012",
    name: "舟山远洋渔业股份有限公司",
    status: "在业",
    creditCode: "91330900MA2XXXXX12",
    legalPerson: "郑海",
    registeredCapital: "15000万元人民币",
    establishDate: "2003-02-28",
    address: "浙江省舟山市定海区临城街道",
    businessScope: "远洋捕捞；水产品加工、冷藏、销售；船舶租赁。",
    province: "浙江省",
  },
];
